# Generated by Django 6.0.6 on 2026-06-16 07:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='taskdate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
